/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.tests;

import co.edu.uniandes.piladsl.tests.PilaInjectorProvider;
import com.google.inject.Inject;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(PilaInjectorProvider.class)
@SuppressWarnings("all")
public class PilaParsingTest {
  @Inject
  private /* ParseHelper<Model> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field PilaParsingTest.parseHelper refers to the missing type Model");
  }
}
