/*
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPilaScopeProvider extends DelegatingScopeProvider {
}
