/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.pila.impl;

import co.edu.uniandes.piladsl.pila.Atributo;
import co.edu.uniandes.piladsl.pila.Entidad;
import co.edu.uniandes.piladsl.pila.LlaveValor;
import co.edu.uniandes.piladsl.pila.PilaPackage;
import co.edu.uniandes.piladsl.pila.TipoDatoPrimitivo;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atributo</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.AtributoImpl#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.AtributoImpl#getTipoPrimitivo <em>Tipo Primitivo</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.AtributoImpl#getListaLlaveValor <em>Lista Llave Valor</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.AtributoImpl#getListaEntidad <em>Lista Entidad</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.AtributoImpl#getReferencia <em>Referencia</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class AtributoImpl extends MinimalEObjectImpl.Container implements Atributo
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getTipoPrimitivo() <em>Tipo Primitivo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoPrimitivo()
   * @generated
   * @ordered
   */
  protected static final TipoDatoPrimitivo TIPO_PRIMITIVO_EDEFAULT = TipoDatoPrimitivo.NO_ASIGNADO;

  /**
   * The cached value of the '{@link #getTipoPrimitivo() <em>Tipo Primitivo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoPrimitivo()
   * @generated
   * @ordered
   */
  protected TipoDatoPrimitivo tipoPrimitivo = TIPO_PRIMITIVO_EDEFAULT;

  /**
   * The cached value of the '{@link #getListaLlaveValor() <em>Lista Llave Valor</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListaLlaveValor()
   * @generated
   * @ordered
   */
  protected EList<LlaveValor> listaLlaveValor;

  /**
   * The cached value of the '{@link #getListaEntidad() <em>Lista Entidad</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListaEntidad()
   * @generated
   * @ordered
   */
  protected Entidad listaEntidad;

  /**
   * The default value of the '{@link #getReferencia() <em>Referencia</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReferencia()
   * @generated
   * @ordered
   */
  protected static final String REFERENCIA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getReferencia() <em>Referencia</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReferencia()
   * @generated
   * @ordered
   */
  protected String referencia = REFERENCIA_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtributoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PilaPackage.Literals.ATRIBUTO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PilaPackage.ATRIBUTO__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TipoDatoPrimitivo getTipoPrimitivo()
  {
    return tipoPrimitivo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTipoPrimitivo(TipoDatoPrimitivo newTipoPrimitivo)
  {
    TipoDatoPrimitivo oldTipoPrimitivo = tipoPrimitivo;
    tipoPrimitivo = newTipoPrimitivo == null ? TIPO_PRIMITIVO_EDEFAULT : newTipoPrimitivo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PilaPackage.ATRIBUTO__TIPO_PRIMITIVO, oldTipoPrimitivo, tipoPrimitivo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<LlaveValor> getListaLlaveValor()
  {
    if (listaLlaveValor == null)
    {
      listaLlaveValor = new EObjectContainmentEList<LlaveValor>(LlaveValor.class, this, PilaPackage.ATRIBUTO__LISTA_LLAVE_VALOR);
    }
    return listaLlaveValor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entidad getListaEntidad()
  {
    if (listaEntidad != null && listaEntidad.eIsProxy())
    {
      InternalEObject oldListaEntidad = (InternalEObject)listaEntidad;
      listaEntidad = (Entidad)eResolveProxy(oldListaEntidad);
      if (listaEntidad != oldListaEntidad)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PilaPackage.ATRIBUTO__LISTA_ENTIDAD, oldListaEntidad, listaEntidad));
      }
    }
    return listaEntidad;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entidad basicGetListaEntidad()
  {
    return listaEntidad;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setListaEntidad(Entidad newListaEntidad)
  {
    Entidad oldListaEntidad = listaEntidad;
    listaEntidad = newListaEntidad;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PilaPackage.ATRIBUTO__LISTA_ENTIDAD, oldListaEntidad, listaEntidad));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getReferencia()
  {
    return referencia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setReferencia(String newReferencia)
  {
    String oldReferencia = referencia;
    referencia = newReferencia;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PilaPackage.ATRIBUTO__REFERENCIA, oldReferencia, referencia));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PilaPackage.ATRIBUTO__LISTA_LLAVE_VALOR:
        return ((InternalEList<?>)getListaLlaveValor()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PilaPackage.ATRIBUTO__NAME:
        return getName();
      case PilaPackage.ATRIBUTO__TIPO_PRIMITIVO:
        return getTipoPrimitivo();
      case PilaPackage.ATRIBUTO__LISTA_LLAVE_VALOR:
        return getListaLlaveValor();
      case PilaPackage.ATRIBUTO__LISTA_ENTIDAD:
        if (resolve) return getListaEntidad();
        return basicGetListaEntidad();
      case PilaPackage.ATRIBUTO__REFERENCIA:
        return getReferencia();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PilaPackage.ATRIBUTO__NAME:
        setName((String)newValue);
        return;
      case PilaPackage.ATRIBUTO__TIPO_PRIMITIVO:
        setTipoPrimitivo((TipoDatoPrimitivo)newValue);
        return;
      case PilaPackage.ATRIBUTO__LISTA_LLAVE_VALOR:
        getListaLlaveValor().clear();
        getListaLlaveValor().addAll((Collection<? extends LlaveValor>)newValue);
        return;
      case PilaPackage.ATRIBUTO__LISTA_ENTIDAD:
        setListaEntidad((Entidad)newValue);
        return;
      case PilaPackage.ATRIBUTO__REFERENCIA:
        setReferencia((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PilaPackage.ATRIBUTO__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PilaPackage.ATRIBUTO__TIPO_PRIMITIVO:
        setTipoPrimitivo(TIPO_PRIMITIVO_EDEFAULT);
        return;
      case PilaPackage.ATRIBUTO__LISTA_LLAVE_VALOR:
        getListaLlaveValor().clear();
        return;
      case PilaPackage.ATRIBUTO__LISTA_ENTIDAD:
        setListaEntidad((Entidad)null);
        return;
      case PilaPackage.ATRIBUTO__REFERENCIA:
        setReferencia(REFERENCIA_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PilaPackage.ATRIBUTO__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PilaPackage.ATRIBUTO__TIPO_PRIMITIVO:
        return tipoPrimitivo != TIPO_PRIMITIVO_EDEFAULT;
      case PilaPackage.ATRIBUTO__LISTA_LLAVE_VALOR:
        return listaLlaveValor != null && !listaLlaveValor.isEmpty();
      case PilaPackage.ATRIBUTO__LISTA_ENTIDAD:
        return listaEntidad != null;
      case PilaPackage.ATRIBUTO__REFERENCIA:
        return REFERENCIA_EDEFAULT == null ? referencia != null : !REFERENCIA_EDEFAULT.equals(referencia);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", tipoPrimitivo: ");
    result.append(tipoPrimitivo);
    result.append(", referencia: ");
    result.append(referencia);
    result.append(')');
    return result.toString();
  }

} //AtributoImpl
