/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.pila.impl;

import co.edu.uniandes.piladsl.pila.Entidad;
import co.edu.uniandes.piladsl.pila.PagoServicio;
import co.edu.uniandes.piladsl.pila.PilaPackage;
import co.edu.uniandes.piladsl.pila.ServicioComputo;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pago Servicio</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.PagoServicioImpl#getEntidades <em>Entidades</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.PagoServicioImpl#getServiciosComputo <em>Servicios Computo</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class PagoServicioImpl extends MinimalEObjectImpl.Container implements PagoServicio
{
  /**
   * The cached value of the '{@link #getEntidades() <em>Entidades</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntidades()
   * @generated
   * @ordered
   */
  protected EList<Entidad> entidades;

  /**
   * The cached value of the '{@link #getServiciosComputo() <em>Servicios Computo</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getServiciosComputo()
   * @generated
   * @ordered
   */
  protected EList<ServicioComputo> serviciosComputo;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PagoServicioImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PilaPackage.Literals.PAGO_SERVICIO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Entidad> getEntidades()
  {
    if (entidades == null)
    {
      entidades = new EObjectContainmentEList<Entidad>(Entidad.class, this, PilaPackage.PAGO_SERVICIO__ENTIDADES);
    }
    return entidades;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ServicioComputo> getServiciosComputo()
  {
    if (serviciosComputo == null)
    {
      serviciosComputo = new EObjectContainmentEList<ServicioComputo>(ServicioComputo.class, this, PilaPackage.PAGO_SERVICIO__SERVICIOS_COMPUTO);
    }
    return serviciosComputo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PilaPackage.PAGO_SERVICIO__ENTIDADES:
        return ((InternalEList<?>)getEntidades()).basicRemove(otherEnd, msgs);
      case PilaPackage.PAGO_SERVICIO__SERVICIOS_COMPUTO:
        return ((InternalEList<?>)getServiciosComputo()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PilaPackage.PAGO_SERVICIO__ENTIDADES:
        return getEntidades();
      case PilaPackage.PAGO_SERVICIO__SERVICIOS_COMPUTO:
        return getServiciosComputo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PilaPackage.PAGO_SERVICIO__ENTIDADES:
        getEntidades().clear();
        getEntidades().addAll((Collection<? extends Entidad>)newValue);
        return;
      case PilaPackage.PAGO_SERVICIO__SERVICIOS_COMPUTO:
        getServiciosComputo().clear();
        getServiciosComputo().addAll((Collection<? extends ServicioComputo>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PilaPackage.PAGO_SERVICIO__ENTIDADES:
        getEntidades().clear();
        return;
      case PilaPackage.PAGO_SERVICIO__SERVICIOS_COMPUTO:
        getServiciosComputo().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PilaPackage.PAGO_SERVICIO__ENTIDADES:
        return entidades != null && !entidades.isEmpty();
      case PilaPackage.PAGO_SERVICIO__SERVICIOS_COMPUTO:
        return serviciosComputo != null && !serviciosComputo.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //PagoServicioImpl
