/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.pila.impl;

import co.edu.uniandes.piladsl.pila.Condicion;
import co.edu.uniandes.piladsl.pila.Expresion;
import co.edu.uniandes.piladsl.pila.PilaPackage;
import co.edu.uniandes.piladsl.pila.ServicioComputo;
import co.edu.uniandes.piladsl.pila.Variable;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Servicio Computo</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.ServicioComputoImpl#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.ServicioComputoImpl#getVariables <em>Variables</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.ServicioComputoImpl#getCondiciones <em>Condiciones</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.ServicioComputoImpl#getExpresionRetorno <em>Expresion Retorno</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class ServicioComputoImpl extends MinimalEObjectImpl.Container implements ServicioComputo
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getVariables() <em>Variables</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariables()
   * @generated
   * @ordered
   */
  protected EList<Variable> variables;

  /**
   * The cached value of the '{@link #getCondiciones() <em>Condiciones</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCondiciones()
   * @generated
   * @ordered
   */
  protected EList<Condicion> condiciones;

  /**
   * The cached value of the '{@link #getExpresionRetorno() <em>Expresion Retorno</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpresionRetorno()
   * @generated
   * @ordered
   */
  protected Expresion expresionRetorno;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ServicioComputoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PilaPackage.Literals.SERVICIO_COMPUTO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PilaPackage.SERVICIO_COMPUTO__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Variable> getVariables()
  {
    if (variables == null)
    {
      variables = new EObjectContainmentEList<Variable>(Variable.class, this, PilaPackage.SERVICIO_COMPUTO__VARIABLES);
    }
    return variables;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Condicion> getCondiciones()
  {
    if (condiciones == null)
    {
      condiciones = new EObjectContainmentEList<Condicion>(Condicion.class, this, PilaPackage.SERVICIO_COMPUTO__CONDICIONES);
    }
    return condiciones;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expresion getExpresionRetorno()
  {
    return expresionRetorno;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpresionRetorno(Expresion newExpresionRetorno, NotificationChain msgs)
  {
    Expresion oldExpresionRetorno = expresionRetorno;
    expresionRetorno = newExpresionRetorno;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PilaPackage.SERVICIO_COMPUTO__EXPRESION_RETORNO, oldExpresionRetorno, newExpresionRetorno);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExpresionRetorno(Expresion newExpresionRetorno)
  {
    if (newExpresionRetorno != expresionRetorno)
    {
      NotificationChain msgs = null;
      if (expresionRetorno != null)
        msgs = ((InternalEObject)expresionRetorno).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PilaPackage.SERVICIO_COMPUTO__EXPRESION_RETORNO, null, msgs);
      if (newExpresionRetorno != null)
        msgs = ((InternalEObject)newExpresionRetorno).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PilaPackage.SERVICIO_COMPUTO__EXPRESION_RETORNO, null, msgs);
      msgs = basicSetExpresionRetorno(newExpresionRetorno, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PilaPackage.SERVICIO_COMPUTO__EXPRESION_RETORNO, newExpresionRetorno, newExpresionRetorno));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PilaPackage.SERVICIO_COMPUTO__VARIABLES:
        return ((InternalEList<?>)getVariables()).basicRemove(otherEnd, msgs);
      case PilaPackage.SERVICIO_COMPUTO__CONDICIONES:
        return ((InternalEList<?>)getCondiciones()).basicRemove(otherEnd, msgs);
      case PilaPackage.SERVICIO_COMPUTO__EXPRESION_RETORNO:
        return basicSetExpresionRetorno(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PilaPackage.SERVICIO_COMPUTO__NAME:
        return getName();
      case PilaPackage.SERVICIO_COMPUTO__VARIABLES:
        return getVariables();
      case PilaPackage.SERVICIO_COMPUTO__CONDICIONES:
        return getCondiciones();
      case PilaPackage.SERVICIO_COMPUTO__EXPRESION_RETORNO:
        return getExpresionRetorno();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PilaPackage.SERVICIO_COMPUTO__NAME:
        setName((String)newValue);
        return;
      case PilaPackage.SERVICIO_COMPUTO__VARIABLES:
        getVariables().clear();
        getVariables().addAll((Collection<? extends Variable>)newValue);
        return;
      case PilaPackage.SERVICIO_COMPUTO__CONDICIONES:
        getCondiciones().clear();
        getCondiciones().addAll((Collection<? extends Condicion>)newValue);
        return;
      case PilaPackage.SERVICIO_COMPUTO__EXPRESION_RETORNO:
        setExpresionRetorno((Expresion)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PilaPackage.SERVICIO_COMPUTO__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PilaPackage.SERVICIO_COMPUTO__VARIABLES:
        getVariables().clear();
        return;
      case PilaPackage.SERVICIO_COMPUTO__CONDICIONES:
        getCondiciones().clear();
        return;
      case PilaPackage.SERVICIO_COMPUTO__EXPRESION_RETORNO:
        setExpresionRetorno((Expresion)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PilaPackage.SERVICIO_COMPUTO__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PilaPackage.SERVICIO_COMPUTO__VARIABLES:
        return variables != null && !variables.isEmpty();
      case PilaPackage.SERVICIO_COMPUTO__CONDICIONES:
        return condiciones != null && !condiciones.isEmpty();
      case PilaPackage.SERVICIO_COMPUTO__EXPRESION_RETORNO:
        return expresionRetorno != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ServicioComputoImpl
