/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.scoping;

import co.edu.uniandes.piladsl.scoping.AbstractPilaScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class PilaScopeProvider extends AbstractPilaScopeProvider {
}
