/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl;

import co.edu.uniandes.piladsl.AbstractPilaRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PilaRuntimeModule extends AbstractPilaRuntimeModule {
}
