/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.pila.impl;

import co.edu.uniandes.piladsl.pila.ExpresionTerminal;
import co.edu.uniandes.piladsl.pila.NombreCalificado;
import co.edu.uniandes.piladsl.pila.PilaPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expresion Terminal</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.ExpresionTerminalImpl#getEntero <em>Entero</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.ExpresionTerminalImpl#getReal <em>Real</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.ExpresionTerminalImpl#getNombreCalificado <em>Nombre Calificado</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class ExpresionTerminalImpl extends MinimalEObjectImpl.Container implements ExpresionTerminal
{
  /**
   * The default value of the '{@link #getEntero() <em>Entero</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntero()
   * @generated
   * @ordered
   */
  protected static final int ENTERO_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getEntero() <em>Entero</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntero()
   * @generated
   * @ordered
   */
  protected int entero = ENTERO_EDEFAULT;

  /**
   * The default value of the '{@link #getReal() <em>Real</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReal()
   * @generated
   * @ordered
   */
  protected static final String REAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getReal() <em>Real</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReal()
   * @generated
   * @ordered
   */
  protected String real = REAL_EDEFAULT;

  /**
   * The cached value of the '{@link #getNombreCalificado() <em>Nombre Calificado</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombreCalificado()
   * @generated
   * @ordered
   */
  protected NombreCalificado nombreCalificado;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpresionTerminalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PilaPackage.Literals.EXPRESION_TERMINAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getEntero()
  {
    return entero;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEntero(int newEntero)
  {
    int oldEntero = entero;
    entero = newEntero;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PilaPackage.EXPRESION_TERMINAL__ENTERO, oldEntero, entero));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getReal()
  {
    return real;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setReal(String newReal)
  {
    String oldReal = real;
    real = newReal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PilaPackage.EXPRESION_TERMINAL__REAL, oldReal, real));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NombreCalificado getNombreCalificado()
  {
    return nombreCalificado;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNombreCalificado(NombreCalificado newNombreCalificado, NotificationChain msgs)
  {
    NombreCalificado oldNombreCalificado = nombreCalificado;
    nombreCalificado = newNombreCalificado;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PilaPackage.EXPRESION_TERMINAL__NOMBRE_CALIFICADO, oldNombreCalificado, newNombreCalificado);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNombreCalificado(NombreCalificado newNombreCalificado)
  {
    if (newNombreCalificado != nombreCalificado)
    {
      NotificationChain msgs = null;
      if (nombreCalificado != null)
        msgs = ((InternalEObject)nombreCalificado).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PilaPackage.EXPRESION_TERMINAL__NOMBRE_CALIFICADO, null, msgs);
      if (newNombreCalificado != null)
        msgs = ((InternalEObject)newNombreCalificado).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PilaPackage.EXPRESION_TERMINAL__NOMBRE_CALIFICADO, null, msgs);
      msgs = basicSetNombreCalificado(newNombreCalificado, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PilaPackage.EXPRESION_TERMINAL__NOMBRE_CALIFICADO, newNombreCalificado, newNombreCalificado));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PilaPackage.EXPRESION_TERMINAL__NOMBRE_CALIFICADO:
        return basicSetNombreCalificado(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PilaPackage.EXPRESION_TERMINAL__ENTERO:
        return getEntero();
      case PilaPackage.EXPRESION_TERMINAL__REAL:
        return getReal();
      case PilaPackage.EXPRESION_TERMINAL__NOMBRE_CALIFICADO:
        return getNombreCalificado();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PilaPackage.EXPRESION_TERMINAL__ENTERO:
        setEntero((Integer)newValue);
        return;
      case PilaPackage.EXPRESION_TERMINAL__REAL:
        setReal((String)newValue);
        return;
      case PilaPackage.EXPRESION_TERMINAL__NOMBRE_CALIFICADO:
        setNombreCalificado((NombreCalificado)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PilaPackage.EXPRESION_TERMINAL__ENTERO:
        setEntero(ENTERO_EDEFAULT);
        return;
      case PilaPackage.EXPRESION_TERMINAL__REAL:
        setReal(REAL_EDEFAULT);
        return;
      case PilaPackage.EXPRESION_TERMINAL__NOMBRE_CALIFICADO:
        setNombreCalificado((NombreCalificado)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PilaPackage.EXPRESION_TERMINAL__ENTERO:
        return entero != ENTERO_EDEFAULT;
      case PilaPackage.EXPRESION_TERMINAL__REAL:
        return REAL_EDEFAULT == null ? real != null : !REAL_EDEFAULT.equals(real);
      case PilaPackage.EXPRESION_TERMINAL__NOMBRE_CALIFICADO:
        return nombreCalificado != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (entero: ");
    result.append(entero);
    result.append(", real: ");
    result.append(real);
    result.append(')');
    return result.toString();
  }

} //ExpresionTerminalImpl
