/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.pila.impl;

import co.edu.uniandes.piladsl.pila.Atributo;
import co.edu.uniandes.piladsl.pila.Condicion;
import co.edu.uniandes.piladsl.pila.Entidad;
import co.edu.uniandes.piladsl.pila.Expresion;
import co.edu.uniandes.piladsl.pila.ExpresionTerminal;
import co.edu.uniandes.piladsl.pila.LlaveValor;
import co.edu.uniandes.piladsl.pila.NombreCalificado;
import co.edu.uniandes.piladsl.pila.Operacion;
import co.edu.uniandes.piladsl.pila.Operador;
import co.edu.uniandes.piladsl.pila.PagoServicio;
import co.edu.uniandes.piladsl.pila.PilaFactory;
import co.edu.uniandes.piladsl.pila.PilaPackage;
import co.edu.uniandes.piladsl.pila.ServicioComputo;
import co.edu.uniandes.piladsl.pila.TipoDatoPrimitivo;
import co.edu.uniandes.piladsl.pila.Variable;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PilaPackageImpl extends EPackageImpl implements PilaPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass pagoServicioEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entidadEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass atributoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass llaveValorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass servicioComputoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass variableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass condicionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expresionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operacionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expresionTerminalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass nombreCalificadoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum tipoDatoPrimitivoEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum operadorEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private PilaPackageImpl()
  {
    super(eNS_URI, PilaFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link PilaPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static PilaPackage init()
  {
    if (isInited) return (PilaPackage)EPackage.Registry.INSTANCE.getEPackage(PilaPackage.eNS_URI);

    // Obtain or create and register package
    PilaPackageImpl thePilaPackage = (PilaPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof PilaPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new PilaPackageImpl());

    isInited = true;

    // Create package meta-data objects
    thePilaPackage.createPackageContents();

    // Initialize created meta-data
    thePilaPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    thePilaPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(PilaPackage.eNS_URI, thePilaPackage);
    return thePilaPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPagoServicio()
  {
    return pagoServicioEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPagoServicio_Entidades()
  {
    return (EReference)pagoServicioEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPagoServicio_ServiciosComputo()
  {
    return (EReference)pagoServicioEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntidad()
  {
    return entidadEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEntidad_Name()
  {
    return (EAttribute)entidadEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntidad_Atributos()
  {
    return (EReference)entidadEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAtributo()
  {
    return atributoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAtributo_Name()
  {
    return (EAttribute)atributoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAtributo_TipoPrimitivo()
  {
    return (EAttribute)atributoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAtributo_ListaLlaveValor()
  {
    return (EReference)atributoEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAtributo_ListaEntidad()
  {
    return (EReference)atributoEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAtributo_Referencia()
  {
    return (EAttribute)atributoEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getLlaveValor()
  {
    return llaveValorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getLlaveValor_Llave()
  {
    return (EAttribute)llaveValorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getLlaveValor_Valor()
  {
    return (EAttribute)llaveValorEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getServicioComputo()
  {
    return servicioComputoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getServicioComputo_Name()
  {
    return (EAttribute)servicioComputoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getServicioComputo_Variables()
  {
    return (EReference)servicioComputoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getServicioComputo_Condiciones()
  {
    return (EReference)servicioComputoEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getServicioComputo_ExpresionRetorno()
  {
    return (EReference)servicioComputoEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getVariable()
  {
    return variableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getVariable_Name()
  {
    return (EAttribute)variableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getVariable_TipoPrimitivo()
  {
    return (EAttribute)variableEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getVariable_ReferenciaEntidad()
  {
    return (EReference)variableEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getVariable_Expresion()
  {
    return (EReference)variableEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCondicion()
  {
    return condicionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCondicion_CondicionSi()
  {
    return (EAttribute)condicionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCondicion_ExpresionCondicion()
  {
    return (EReference)condicionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCondicion_CondicionSiNinguno()
  {
    return (EAttribute)condicionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCondicion_Variables()
  {
    return (EReference)condicionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCondicion_AsignacionVariable()
  {
    return (EReference)condicionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCondicion_ExpresionAsignacionVariable()
  {
    return (EReference)condicionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCondicion_SubCondiciones()
  {
    return (EReference)condicionEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCondicion_ExpresionRetorno()
  {
    return (EReference)condicionEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpresion()
  {
    return expresionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpresion_ExpresionTerminal()
  {
    return (EReference)expresionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpresion_Operacion()
  {
    return (EReference)expresionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getOperacion()
  {
    return operacionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getOperacion_Izquierda()
  {
    return (EReference)operacionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getOperacion_Operador()
  {
    return (EAttribute)operacionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getOperacion_Derecha()
  {
    return (EReference)operacionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpresionTerminal()
  {
    return expresionTerminalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getExpresionTerminal_Entero()
  {
    return (EAttribute)expresionTerminalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getExpresionTerminal_Real()
  {
    return (EAttribute)expresionTerminalEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpresionTerminal_NombreCalificado()
  {
    return (EReference)expresionTerminalEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getNombreCalificado()
  {
    return nombreCalificadoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getNombreCalificado_Ides()
  {
    return (EAttribute)nombreCalificadoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getTipoDatoPrimitivo()
  {
    return tipoDatoPrimitivoEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getOperador()
  {
    return operadorEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PilaFactory getPilaFactory()
  {
    return (PilaFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    pagoServicioEClass = createEClass(PAGO_SERVICIO);
    createEReference(pagoServicioEClass, PAGO_SERVICIO__ENTIDADES);
    createEReference(pagoServicioEClass, PAGO_SERVICIO__SERVICIOS_COMPUTO);

    entidadEClass = createEClass(ENTIDAD);
    createEAttribute(entidadEClass, ENTIDAD__NAME);
    createEReference(entidadEClass, ENTIDAD__ATRIBUTOS);

    atributoEClass = createEClass(ATRIBUTO);
    createEAttribute(atributoEClass, ATRIBUTO__NAME);
    createEAttribute(atributoEClass, ATRIBUTO__TIPO_PRIMITIVO);
    createEReference(atributoEClass, ATRIBUTO__LISTA_LLAVE_VALOR);
    createEReference(atributoEClass, ATRIBUTO__LISTA_ENTIDAD);
    createEAttribute(atributoEClass, ATRIBUTO__REFERENCIA);

    llaveValorEClass = createEClass(LLAVE_VALOR);
    createEAttribute(llaveValorEClass, LLAVE_VALOR__LLAVE);
    createEAttribute(llaveValorEClass, LLAVE_VALOR__VALOR);

    servicioComputoEClass = createEClass(SERVICIO_COMPUTO);
    createEAttribute(servicioComputoEClass, SERVICIO_COMPUTO__NAME);
    createEReference(servicioComputoEClass, SERVICIO_COMPUTO__VARIABLES);
    createEReference(servicioComputoEClass, SERVICIO_COMPUTO__CONDICIONES);
    createEReference(servicioComputoEClass, SERVICIO_COMPUTO__EXPRESION_RETORNO);

    variableEClass = createEClass(VARIABLE);
    createEAttribute(variableEClass, VARIABLE__NAME);
    createEAttribute(variableEClass, VARIABLE__TIPO_PRIMITIVO);
    createEReference(variableEClass, VARIABLE__REFERENCIA_ENTIDAD);
    createEReference(variableEClass, VARIABLE__EXPRESION);

    condicionEClass = createEClass(CONDICION);
    createEAttribute(condicionEClass, CONDICION__CONDICION_SI);
    createEReference(condicionEClass, CONDICION__EXPRESION_CONDICION);
    createEAttribute(condicionEClass, CONDICION__CONDICION_SI_NINGUNO);
    createEReference(condicionEClass, CONDICION__VARIABLES);
    createEReference(condicionEClass, CONDICION__ASIGNACION_VARIABLE);
    createEReference(condicionEClass, CONDICION__EXPRESION_ASIGNACION_VARIABLE);
    createEReference(condicionEClass, CONDICION__SUB_CONDICIONES);
    createEReference(condicionEClass, CONDICION__EXPRESION_RETORNO);

    expresionEClass = createEClass(EXPRESION);
    createEReference(expresionEClass, EXPRESION__EXPRESION_TERMINAL);
    createEReference(expresionEClass, EXPRESION__OPERACION);

    operacionEClass = createEClass(OPERACION);
    createEReference(operacionEClass, OPERACION__IZQUIERDA);
    createEAttribute(operacionEClass, OPERACION__OPERADOR);
    createEReference(operacionEClass, OPERACION__DERECHA);

    expresionTerminalEClass = createEClass(EXPRESION_TERMINAL);
    createEAttribute(expresionTerminalEClass, EXPRESION_TERMINAL__ENTERO);
    createEAttribute(expresionTerminalEClass, EXPRESION_TERMINAL__REAL);
    createEReference(expresionTerminalEClass, EXPRESION_TERMINAL__NOMBRE_CALIFICADO);

    nombreCalificadoEClass = createEClass(NOMBRE_CALIFICADO);
    createEAttribute(nombreCalificadoEClass, NOMBRE_CALIFICADO__IDES);

    // Create enums
    tipoDatoPrimitivoEEnum = createEEnum(TIPO_DATO_PRIMITIVO);
    operadorEEnum = createEEnum(OPERADOR);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(pagoServicioEClass, PagoServicio.class, "PagoServicio", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPagoServicio_Entidades(), this.getEntidad(), null, "entidades", null, 0, -1, PagoServicio.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPagoServicio_ServiciosComputo(), this.getServicioComputo(), null, "serviciosComputo", null, 0, -1, PagoServicio.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entidadEClass, Entidad.class, "Entidad", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEntidad_Name(), ecorePackage.getEString(), "name", null, 0, 1, Entidad.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntidad_Atributos(), this.getAtributo(), null, "atributos", null, 0, -1, Entidad.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(atributoEClass, Atributo.class, "Atributo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAtributo_Name(), ecorePackage.getEString(), "name", null, 0, 1, Atributo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAtributo_TipoPrimitivo(), this.getTipoDatoPrimitivo(), "tipoPrimitivo", null, 0, 1, Atributo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAtributo_ListaLlaveValor(), this.getLlaveValor(), null, "listaLlaveValor", null, 0, -1, Atributo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAtributo_ListaEntidad(), this.getEntidad(), null, "listaEntidad", null, 0, 1, Atributo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAtributo_Referencia(), ecorePackage.getEString(), "referencia", null, 0, 1, Atributo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(llaveValorEClass, LlaveValor.class, "LlaveValor", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLlaveValor_Llave(), ecorePackage.getEInt(), "llave", null, 0, 1, LlaveValor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLlaveValor_Valor(), ecorePackage.getEString(), "valor", null, 0, 1, LlaveValor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(servicioComputoEClass, ServicioComputo.class, "ServicioComputo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getServicioComputo_Name(), ecorePackage.getEString(), "name", null, 0, 1, ServicioComputo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getServicioComputo_Variables(), this.getVariable(), null, "variables", null, 0, -1, ServicioComputo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getServicioComputo_Condiciones(), this.getCondicion(), null, "condiciones", null, 0, -1, ServicioComputo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getServicioComputo_ExpresionRetorno(), this.getExpresion(), null, "expresionRetorno", null, 0, 1, ServicioComputo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(variableEClass, Variable.class, "Variable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVariable_Name(), ecorePackage.getEString(), "name", null, 0, 1, Variable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVariable_TipoPrimitivo(), this.getTipoDatoPrimitivo(), "tipoPrimitivo", null, 0, 1, Variable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVariable_ReferenciaEntidad(), this.getEntidad(), null, "referenciaEntidad", null, 0, 1, Variable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVariable_Expresion(), this.getExpresion(), null, "expresion", null, 0, 1, Variable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(condicionEClass, Condicion.class, "Condicion", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCondicion_CondicionSi(), ecorePackage.getEString(), "condicionSi", null, 0, 1, Condicion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCondicion_ExpresionCondicion(), this.getExpresion(), null, "expresionCondicion", null, 0, 1, Condicion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCondicion_CondicionSiNinguno(), ecorePackage.getEString(), "condicionSiNinguno", null, 0, 1, Condicion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCondicion_Variables(), this.getVariable(), null, "variables", null, 0, -1, Condicion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCondicion_AsignacionVariable(), this.getVariable(), null, "asignacionVariable", null, 0, 1, Condicion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCondicion_ExpresionAsignacionVariable(), this.getExpresion(), null, "expresionAsignacionVariable", null, 0, 1, Condicion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCondicion_SubCondiciones(), this.getCondicion(), null, "subCondiciones", null, 0, -1, Condicion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCondicion_ExpresionRetorno(), this.getExpresion(), null, "expresionRetorno", null, 0, 1, Condicion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expresionEClass, Expresion.class, "Expresion", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpresion_ExpresionTerminal(), this.getExpresionTerminal(), null, "expresionTerminal", null, 0, 1, Expresion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpresion_Operacion(), this.getOperacion(), null, "operacion", null, 0, 1, Expresion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(operacionEClass, Operacion.class, "Operacion", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOperacion_Izquierda(), this.getExpresionTerminal(), null, "izquierda", null, 0, 1, Operacion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getOperacion_Operador(), this.getOperador(), "operador", null, 0, 1, Operacion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getOperacion_Derecha(), this.getExpresionTerminal(), null, "derecha", null, 0, 1, Operacion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expresionTerminalEClass, ExpresionTerminal.class, "ExpresionTerminal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getExpresionTerminal_Entero(), ecorePackage.getEInt(), "entero", null, 0, 1, ExpresionTerminal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExpresionTerminal_Real(), ecorePackage.getEString(), "real", null, 0, 1, ExpresionTerminal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExpresionTerminal_NombreCalificado(), this.getNombreCalificado(), null, "nombreCalificado", null, 0, 1, ExpresionTerminal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(nombreCalificadoEClass, NombreCalificado.class, "NombreCalificado", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNombreCalificado_Ides(), ecorePackage.getEString(), "ides", null, 0, -1, NombreCalificado.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(tipoDatoPrimitivoEEnum, TipoDatoPrimitivo.class, "TipoDatoPrimitivo");
    addEEnumLiteral(tipoDatoPrimitivoEEnum, TipoDatoPrimitivo.NO_ASIGNADO);
    addEEnumLiteral(tipoDatoPrimitivoEEnum, TipoDatoPrimitivo.CADENA_CARACTERES);
    addEEnumLiteral(tipoDatoPrimitivoEEnum, TipoDatoPrimitivo.ENTERO);
    addEEnumLiteral(tipoDatoPrimitivoEEnum, TipoDatoPrimitivo.FLOTANTE);
    addEEnumLiteral(tipoDatoPrimitivoEEnum, TipoDatoPrimitivo.FECHA);
    addEEnumLiteral(tipoDatoPrimitivoEEnum, TipoDatoPrimitivo.BOOLEANO);

    initEEnum(operadorEEnum, Operador.class, "Operador");
    addEEnumLiteral(operadorEEnum, Operador.SUMA);
    addEEnumLiteral(operadorEEnum, Operador.RESTA);
    addEEnumLiteral(operadorEEnum, Operador.MULTIPLICACION);
    addEEnumLiteral(operadorEEnum, Operador.DIVISION);
    addEEnumLiteral(operadorEEnum, Operador.IGUAL);
    addEEnumLiteral(operadorEEnum, Operador.DIFERENTE);
    addEEnumLiteral(operadorEEnum, Operador.MAYOR);
    addEEnumLiteral(operadorEEnum, Operador.MAYOR_IGUAL);
    addEEnumLiteral(operadorEEnum, Operador.MENOR);
    addEEnumLiteral(operadorEEnum, Operador.MENOR_IGUAL);
    addEEnumLiteral(operadorEEnum, Operador.Y);
    addEEnumLiteral(operadorEEnum, Operador.O);

    // Create resource
    createResource(eNS_URI);
  }

} //PilaPackageImpl
