/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.pila.impl;

import co.edu.uniandes.piladsl.pila.Entidad;
import co.edu.uniandes.piladsl.pila.Expresion;
import co.edu.uniandes.piladsl.pila.PilaPackage;
import co.edu.uniandes.piladsl.pila.TipoDatoPrimitivo;
import co.edu.uniandes.piladsl.pila.Variable;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Variable</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.VariableImpl#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.VariableImpl#getTipoPrimitivo <em>Tipo Primitivo</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.VariableImpl#getReferenciaEntidad <em>Referencia Entidad</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.impl.VariableImpl#getExpresion <em>Expresion</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class VariableImpl extends MinimalEObjectImpl.Container implements Variable
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getTipoPrimitivo() <em>Tipo Primitivo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoPrimitivo()
   * @generated
   * @ordered
   */
  protected static final TipoDatoPrimitivo TIPO_PRIMITIVO_EDEFAULT = TipoDatoPrimitivo.NO_ASIGNADO;

  /**
   * The cached value of the '{@link #getTipoPrimitivo() <em>Tipo Primitivo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoPrimitivo()
   * @generated
   * @ordered
   */
  protected TipoDatoPrimitivo tipoPrimitivo = TIPO_PRIMITIVO_EDEFAULT;

  /**
   * The cached value of the '{@link #getReferenciaEntidad() <em>Referencia Entidad</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReferenciaEntidad()
   * @generated
   * @ordered
   */
  protected Entidad referenciaEntidad;

  /**
   * The cached value of the '{@link #getExpresion() <em>Expresion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpresion()
   * @generated
   * @ordered
   */
  protected Expresion expresion;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VariableImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PilaPackage.Literals.VARIABLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PilaPackage.VARIABLE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TipoDatoPrimitivo getTipoPrimitivo()
  {
    return tipoPrimitivo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTipoPrimitivo(TipoDatoPrimitivo newTipoPrimitivo)
  {
    TipoDatoPrimitivo oldTipoPrimitivo = tipoPrimitivo;
    tipoPrimitivo = newTipoPrimitivo == null ? TIPO_PRIMITIVO_EDEFAULT : newTipoPrimitivo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PilaPackage.VARIABLE__TIPO_PRIMITIVO, oldTipoPrimitivo, tipoPrimitivo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entidad getReferenciaEntidad()
  {
    if (referenciaEntidad != null && referenciaEntidad.eIsProxy())
    {
      InternalEObject oldReferenciaEntidad = (InternalEObject)referenciaEntidad;
      referenciaEntidad = (Entidad)eResolveProxy(oldReferenciaEntidad);
      if (referenciaEntidad != oldReferenciaEntidad)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PilaPackage.VARIABLE__REFERENCIA_ENTIDAD, oldReferenciaEntidad, referenciaEntidad));
      }
    }
    return referenciaEntidad;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entidad basicGetReferenciaEntidad()
  {
    return referenciaEntidad;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setReferenciaEntidad(Entidad newReferenciaEntidad)
  {
    Entidad oldReferenciaEntidad = referenciaEntidad;
    referenciaEntidad = newReferenciaEntidad;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PilaPackage.VARIABLE__REFERENCIA_ENTIDAD, oldReferenciaEntidad, referenciaEntidad));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expresion getExpresion()
  {
    return expresion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpresion(Expresion newExpresion, NotificationChain msgs)
  {
    Expresion oldExpresion = expresion;
    expresion = newExpresion;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PilaPackage.VARIABLE__EXPRESION, oldExpresion, newExpresion);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExpresion(Expresion newExpresion)
  {
    if (newExpresion != expresion)
    {
      NotificationChain msgs = null;
      if (expresion != null)
        msgs = ((InternalEObject)expresion).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PilaPackage.VARIABLE__EXPRESION, null, msgs);
      if (newExpresion != null)
        msgs = ((InternalEObject)newExpresion).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PilaPackage.VARIABLE__EXPRESION, null, msgs);
      msgs = basicSetExpresion(newExpresion, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PilaPackage.VARIABLE__EXPRESION, newExpresion, newExpresion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PilaPackage.VARIABLE__EXPRESION:
        return basicSetExpresion(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PilaPackage.VARIABLE__NAME:
        return getName();
      case PilaPackage.VARIABLE__TIPO_PRIMITIVO:
        return getTipoPrimitivo();
      case PilaPackage.VARIABLE__REFERENCIA_ENTIDAD:
        if (resolve) return getReferenciaEntidad();
        return basicGetReferenciaEntidad();
      case PilaPackage.VARIABLE__EXPRESION:
        return getExpresion();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PilaPackage.VARIABLE__NAME:
        setName((String)newValue);
        return;
      case PilaPackage.VARIABLE__TIPO_PRIMITIVO:
        setTipoPrimitivo((TipoDatoPrimitivo)newValue);
        return;
      case PilaPackage.VARIABLE__REFERENCIA_ENTIDAD:
        setReferenciaEntidad((Entidad)newValue);
        return;
      case PilaPackage.VARIABLE__EXPRESION:
        setExpresion((Expresion)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PilaPackage.VARIABLE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PilaPackage.VARIABLE__TIPO_PRIMITIVO:
        setTipoPrimitivo(TIPO_PRIMITIVO_EDEFAULT);
        return;
      case PilaPackage.VARIABLE__REFERENCIA_ENTIDAD:
        setReferenciaEntidad((Entidad)null);
        return;
      case PilaPackage.VARIABLE__EXPRESION:
        setExpresion((Expresion)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PilaPackage.VARIABLE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PilaPackage.VARIABLE__TIPO_PRIMITIVO:
        return tipoPrimitivo != TIPO_PRIMITIVO_EDEFAULT;
      case PilaPackage.VARIABLE__REFERENCIA_ENTIDAD:
        return referenciaEntidad != null;
      case PilaPackage.VARIABLE__EXPRESION:
        return expresion != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", tipoPrimitivo: ");
    result.append(tipoPrimitivo);
    result.append(')');
    return result.toString();
  }

} //VariableImpl
