/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.ui.contentassist;

import co.edu.uniandes.piladsl.ui.contentassist.AbstractPilaProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PilaProposalProvider extends AbstractPilaProposalProvider {
}
