/*
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.parser.antlr;

import co.edu.uniandes.piladsl.parser.antlr.internal.InternalPilaParser;
import co.edu.uniandes.piladsl.services.PilaGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PilaParser extends AbstractAntlrParser {

	@Inject
	private PilaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPilaParser createParser(XtextTokenStream stream) {
		return new InternalPilaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "PagoServicio";
	}

	public PilaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PilaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
