/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.pila;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expresion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link co.edu.uniandes.piladsl.pila.Expresion#getIzquierda <em>Izquierda</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.Expresion#getOperador <em>Operador</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.Expresion#getDerechas <em>Derechas</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.Expresion#getEntero <em>Entero</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.Expresion#getReal <em>Real</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.Expresion#getNombreCalificado <em>Nombre Calificado</em>}</li>
 * </ul>
 * </p>
 *
 * @see co.edu.uniandes.piladsl.pila.PilaPackage#getExpresion()
 * @model
 * @generated
 */
public interface Expresion extends EObject
{
  /**
   * Returns the value of the '<em><b>Izquierda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Izquierda</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Izquierda</em>' containment reference.
   * @see #setIzquierda(Expresion)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getExpresion_Izquierda()
   * @model containment="true"
   * @generated
   */
  Expresion getIzquierda();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.Expresion#getIzquierda <em>Izquierda</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Izquierda</em>' containment reference.
   * @see #getIzquierda()
   * @generated
   */
  void setIzquierda(Expresion value);

  /**
   * Returns the value of the '<em><b>Operador</b></em>' attribute list.
   * The list contents are of type {@link co.edu.uniandes.piladsl.pila.Operador}.
   * The literals are from the enumeration {@link co.edu.uniandes.piladsl.pila.Operador}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operador</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operador</em>' attribute list.
   * @see co.edu.uniandes.piladsl.pila.Operador
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getExpresion_Operador()
   * @model unique="false"
   * @generated
   */
  EList<Operador> getOperador();

  /**
   * Returns the value of the '<em><b>Derechas</b></em>' containment reference list.
   * The list contents are of type {@link co.edu.uniandes.piladsl.pila.Expresion}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Derechas</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Derechas</em>' containment reference list.
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getExpresion_Derechas()
   * @model containment="true"
   * @generated
   */
  EList<Expresion> getDerechas();

  /**
   * Returns the value of the '<em><b>Entero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entero</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entero</em>' attribute.
   * @see #setEntero(int)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getExpresion_Entero()
   * @model
   * @generated
   */
  int getEntero();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.Expresion#getEntero <em>Entero</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entero</em>' attribute.
   * @see #getEntero()
   * @generated
   */
  void setEntero(int value);

  /**
   * Returns the value of the '<em><b>Real</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Real</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Real</em>' attribute.
   * @see #setReal(int)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getExpresion_Real()
   * @model
   * @generated
   */
  int getReal();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.Expresion#getReal <em>Real</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Real</em>' attribute.
   * @see #getReal()
   * @generated
   */
  void setReal(int value);

  /**
   * Returns the value of the '<em><b>Nombre Calificado</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nombre Calificado</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre Calificado</em>' containment reference.
   * @see #setNombreCalificado(NombreCalificado)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getExpresion_NombreCalificado()
   * @model containment="true"
   * @generated
   */
  NombreCalificado getNombreCalificado();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.Expresion#getNombreCalificado <em>Nombre Calificado</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre Calificado</em>' containment reference.
   * @see #getNombreCalificado()
   * @generated
   */
  void setNombreCalificado(NombreCalificado value);

} // Expresion
