/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.pila;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Llave Valor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link co.edu.uniandes.piladsl.pila.LlaveValor#getLlave <em>Llave</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.LlaveValor#getValor <em>Valor</em>}</li>
 * </ul>
 * </p>
 *
 * @see co.edu.uniandes.piladsl.pila.PilaPackage#getLlaveValor()
 * @model
 * @generated
 */
public interface LlaveValor extends EObject
{
  /**
   * Returns the value of the '<em><b>Llave</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Llave</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Llave</em>' attribute.
   * @see #setLlave(int)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getLlaveValor_Llave()
   * @model
   * @generated
   */
  int getLlave();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.LlaveValor#getLlave <em>Llave</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Llave</em>' attribute.
   * @see #getLlave()
   * @generated
   */
  void setLlave(int value);

  /**
   * Returns the value of the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Valor</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valor</em>' attribute.
   * @see #setValor(String)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getLlaveValor_Valor()
   * @model
   * @generated
   */
  String getValor();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.LlaveValor#getValor <em>Valor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valor</em>' attribute.
   * @see #getValor()
   * @generated
   */
  void setValor(String value);

} // LlaveValor
