/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.pila;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nombre Calificado</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link co.edu.uniandes.piladsl.pila.NombreCalificado#getIdes <em>Ides</em>}</li>
 * </ul>
 * </p>
 *
 * @see co.edu.uniandes.piladsl.pila.PilaPackage#getNombreCalificado()
 * @model
 * @generated
 */
public interface NombreCalificado extends EObject
{
  /**
   * Returns the value of the '<em><b>Ides</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ides</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ides</em>' attribute list.
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getNombreCalificado_Ides()
   * @model unique="false"
   * @generated
   */
  EList<String> getIdes();

} // NombreCalificado
