/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.pila;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see co.edu.uniandes.piladsl.pila.PilaFactory
 * @model kind="package"
 * @generated
 */
public interface PilaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "pila";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://co.edu.uniandes.pila";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "pila";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PilaPackage eINSTANCE = co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl.init();

  /**
   * The meta object id for the '{@link co.edu.uniandes.piladsl.pila.impl.PagoServicioImpl <em>Pago Servicio</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.piladsl.pila.impl.PagoServicioImpl
   * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getPagoServicio()
   * @generated
   */
  int PAGO_SERVICIO = 0;

  /**
   * The feature id for the '<em><b>Entidades</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGO_SERVICIO__ENTIDADES = 0;

  /**
   * The feature id for the '<em><b>Servicios Computo</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGO_SERVICIO__SERVICIOS_COMPUTO = 1;

  /**
   * The number of structural features of the '<em>Pago Servicio</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGO_SERVICIO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.uniandes.piladsl.pila.impl.EntidadImpl <em>Entidad</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.piladsl.pila.impl.EntidadImpl
   * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getEntidad()
   * @generated
   */
  int ENTIDAD = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD__NAME = 0;

  /**
   * The feature id for the '<em><b>Atributos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD__ATRIBUTOS = 1;

  /**
   * The number of structural features of the '<em>Entidad</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.uniandes.piladsl.pila.impl.AtributoImpl <em>Atributo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.piladsl.pila.impl.AtributoImpl
   * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getAtributo()
   * @generated
   */
  int ATRIBUTO = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__NAME = 0;

  /**
   * The feature id for the '<em><b>Tipo Primitivo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__TIPO_PRIMITIVO = 1;

  /**
   * The feature id for the '<em><b>Lista Llave Valor</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__LISTA_LLAVE_VALOR = 2;

  /**
   * The feature id for the '<em><b>Lista Entidad</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__LISTA_ENTIDAD = 3;

  /**
   * The feature id for the '<em><b>Referencia</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__REFERENCIA = 4;

  /**
   * The number of structural features of the '<em>Atributo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link co.edu.uniandes.piladsl.pila.impl.LlaveValorImpl <em>Llave Valor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.piladsl.pila.impl.LlaveValorImpl
   * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getLlaveValor()
   * @generated
   */
  int LLAVE_VALOR = 3;

  /**
   * The feature id for the '<em><b>Llave</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LLAVE_VALOR__LLAVE = 0;

  /**
   * The feature id for the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LLAVE_VALOR__VALOR = 1;

  /**
   * The number of structural features of the '<em>Llave Valor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LLAVE_VALOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.uniandes.piladsl.pila.impl.ServicioComputoImpl <em>Servicio Computo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.piladsl.pila.impl.ServicioComputoImpl
   * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getServicioComputo()
   * @generated
   */
  int SERVICIO_COMPUTO = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICIO_COMPUTO__NAME = 0;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICIO_COMPUTO__VARIABLES = 1;

  /**
   * The feature id for the '<em><b>Condiciones</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICIO_COMPUTO__CONDICIONES = 2;

  /**
   * The feature id for the '<em><b>Expresion Retorno</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICIO_COMPUTO__EXPRESION_RETORNO = 3;

  /**
   * The number of structural features of the '<em>Servicio Computo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICIO_COMPUTO_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link co.edu.uniandes.piladsl.pila.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.piladsl.pila.impl.VariableImpl
   * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Tipo Primitivo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__TIPO_PRIMITIVO = 1;

  /**
   * The feature id for the '<em><b>Referencia Entidad</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__REFERENCIA_ENTIDAD = 2;

  /**
   * The feature id for the '<em><b>Expresion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__EXPRESION = 3;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link co.edu.uniandes.piladsl.pila.impl.CondicionImpl <em>Condicion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.piladsl.pila.impl.CondicionImpl
   * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getCondicion()
   * @generated
   */
  int CONDICION = 6;

  /**
   * The feature id for the '<em><b>Condicion Si</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICION__CONDICION_SI = 0;

  /**
   * The feature id for the '<em><b>Expresion Condicion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICION__EXPRESION_CONDICION = 1;

  /**
   * The feature id for the '<em><b>Condicion Si Ninguno</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICION__CONDICION_SI_NINGUNO = 2;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICION__VARIABLES = 3;

  /**
   * The feature id for the '<em><b>Asignacion Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICION__ASIGNACION_VARIABLE = 4;

  /**
   * The feature id for the '<em><b>Expresion</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICION__EXPRESION = 5;

  /**
   * The feature id for the '<em><b>Sub Condiciones</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICION__SUB_CONDICIONES = 6;

  /**
   * The feature id for the '<em><b>Expresion Retorno</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICION__EXPRESION_RETORNO = 7;

  /**
   * The number of structural features of the '<em>Condicion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICION_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link co.edu.uniandes.piladsl.pila.impl.ExpresionImpl <em>Expresion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.piladsl.pila.impl.ExpresionImpl
   * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getExpresion()
   * @generated
   */
  int EXPRESION = 7;

  /**
   * The feature id for the '<em><b>Izquierda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__IZQUIERDA = 0;

  /**
   * The feature id for the '<em><b>Operador</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__OPERADOR = 1;

  /**
   * The feature id for the '<em><b>Derechas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__DERECHAS = 2;

  /**
   * The feature id for the '<em><b>Entero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__ENTERO = 3;

  /**
   * The feature id for the '<em><b>Real</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__REAL = 4;

  /**
   * The feature id for the '<em><b>Nombre Calificado</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION__NOMBRE_CALIFICADO = 5;

  /**
   * The number of structural features of the '<em>Expresion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link co.edu.uniandes.piladsl.pila.impl.NombreCalificadoImpl <em>Nombre Calificado</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.piladsl.pila.impl.NombreCalificadoImpl
   * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getNombreCalificado()
   * @generated
   */
  int NOMBRE_CALIFICADO = 8;

  /**
   * The feature id for the '<em><b>Ides</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOMBRE_CALIFICADO__IDES = 0;

  /**
   * The number of structural features of the '<em>Nombre Calificado</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOMBRE_CALIFICADO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link co.edu.uniandes.piladsl.pila.TipoDatoPrimitivo <em>Tipo Dato Primitivo</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.piladsl.pila.TipoDatoPrimitivo
   * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getTipoDatoPrimitivo()
   * @generated
   */
  int TIPO_DATO_PRIMITIVO = 9;

  /**
   * The meta object id for the '{@link co.edu.uniandes.piladsl.pila.Operador <em>Operador</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.uniandes.piladsl.pila.Operador
   * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getOperador()
   * @generated
   */
  int OPERADOR = 10;


  /**
   * Returns the meta object for class '{@link co.edu.uniandes.piladsl.pila.PagoServicio <em>Pago Servicio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pago Servicio</em>'.
   * @see co.edu.uniandes.piladsl.pila.PagoServicio
   * @generated
   */
  EClass getPagoServicio();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.uniandes.piladsl.pila.PagoServicio#getEntidades <em>Entidades</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entidades</em>'.
   * @see co.edu.uniandes.piladsl.pila.PagoServicio#getEntidades()
   * @see #getPagoServicio()
   * @generated
   */
  EReference getPagoServicio_Entidades();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.uniandes.piladsl.pila.PagoServicio#getServiciosComputo <em>Servicios Computo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Servicios Computo</em>'.
   * @see co.edu.uniandes.piladsl.pila.PagoServicio#getServiciosComputo()
   * @see #getPagoServicio()
   * @generated
   */
  EReference getPagoServicio_ServiciosComputo();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.piladsl.pila.Entidad <em>Entidad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entidad</em>'.
   * @see co.edu.uniandes.piladsl.pila.Entidad
   * @generated
   */
  EClass getEntidad();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.piladsl.pila.Entidad#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.uniandes.piladsl.pila.Entidad#getName()
   * @see #getEntidad()
   * @generated
   */
  EAttribute getEntidad_Name();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.uniandes.piladsl.pila.Entidad#getAtributos <em>Atributos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Atributos</em>'.
   * @see co.edu.uniandes.piladsl.pila.Entidad#getAtributos()
   * @see #getEntidad()
   * @generated
   */
  EReference getEntidad_Atributos();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.piladsl.pila.Atributo <em>Atributo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atributo</em>'.
   * @see co.edu.uniandes.piladsl.pila.Atributo
   * @generated
   */
  EClass getAtributo();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.piladsl.pila.Atributo#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.uniandes.piladsl.pila.Atributo#getName()
   * @see #getAtributo()
   * @generated
   */
  EAttribute getAtributo_Name();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.piladsl.pila.Atributo#getTipoPrimitivo <em>Tipo Primitivo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo Primitivo</em>'.
   * @see co.edu.uniandes.piladsl.pila.Atributo#getTipoPrimitivo()
   * @see #getAtributo()
   * @generated
   */
  EAttribute getAtributo_TipoPrimitivo();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.uniandes.piladsl.pila.Atributo#getListaLlaveValor <em>Lista Llave Valor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lista Llave Valor</em>'.
   * @see co.edu.uniandes.piladsl.pila.Atributo#getListaLlaveValor()
   * @see #getAtributo()
   * @generated
   */
  EReference getAtributo_ListaLlaveValor();

  /**
   * Returns the meta object for the reference '{@link co.edu.uniandes.piladsl.pila.Atributo#getListaEntidad <em>Lista Entidad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Lista Entidad</em>'.
   * @see co.edu.uniandes.piladsl.pila.Atributo#getListaEntidad()
   * @see #getAtributo()
   * @generated
   */
  EReference getAtributo_ListaEntidad();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.piladsl.pila.Atributo#getReferencia <em>Referencia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Referencia</em>'.
   * @see co.edu.uniandes.piladsl.pila.Atributo#getReferencia()
   * @see #getAtributo()
   * @generated
   */
  EAttribute getAtributo_Referencia();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.piladsl.pila.LlaveValor <em>Llave Valor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Llave Valor</em>'.
   * @see co.edu.uniandes.piladsl.pila.LlaveValor
   * @generated
   */
  EClass getLlaveValor();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.piladsl.pila.LlaveValor#getLlave <em>Llave</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Llave</em>'.
   * @see co.edu.uniandes.piladsl.pila.LlaveValor#getLlave()
   * @see #getLlaveValor()
   * @generated
   */
  EAttribute getLlaveValor_Llave();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.piladsl.pila.LlaveValor#getValor <em>Valor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valor</em>'.
   * @see co.edu.uniandes.piladsl.pila.LlaveValor#getValor()
   * @see #getLlaveValor()
   * @generated
   */
  EAttribute getLlaveValor_Valor();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.piladsl.pila.ServicioComputo <em>Servicio Computo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Servicio Computo</em>'.
   * @see co.edu.uniandes.piladsl.pila.ServicioComputo
   * @generated
   */
  EClass getServicioComputo();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.piladsl.pila.ServicioComputo#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.uniandes.piladsl.pila.ServicioComputo#getName()
   * @see #getServicioComputo()
   * @generated
   */
  EAttribute getServicioComputo_Name();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.uniandes.piladsl.pila.ServicioComputo#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see co.edu.uniandes.piladsl.pila.ServicioComputo#getVariables()
   * @see #getServicioComputo()
   * @generated
   */
  EReference getServicioComputo_Variables();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.uniandes.piladsl.pila.ServicioComputo#getCondiciones <em>Condiciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Condiciones</em>'.
   * @see co.edu.uniandes.piladsl.pila.ServicioComputo#getCondiciones()
   * @see #getServicioComputo()
   * @generated
   */
  EReference getServicioComputo_Condiciones();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.uniandes.piladsl.pila.ServicioComputo#getExpresionRetorno <em>Expresion Retorno</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expresion Retorno</em>'.
   * @see co.edu.uniandes.piladsl.pila.ServicioComputo#getExpresionRetorno()
   * @see #getServicioComputo()
   * @generated
   */
  EReference getServicioComputo_ExpresionRetorno();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.piladsl.pila.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see co.edu.uniandes.piladsl.pila.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.piladsl.pila.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.uniandes.piladsl.pila.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.piladsl.pila.Variable#getTipoPrimitivo <em>Tipo Primitivo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo Primitivo</em>'.
   * @see co.edu.uniandes.piladsl.pila.Variable#getTipoPrimitivo()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_TipoPrimitivo();

  /**
   * Returns the meta object for the reference '{@link co.edu.uniandes.piladsl.pila.Variable#getReferenciaEntidad <em>Referencia Entidad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Referencia Entidad</em>'.
   * @see co.edu.uniandes.piladsl.pila.Variable#getReferenciaEntidad()
   * @see #getVariable()
   * @generated
   */
  EReference getVariable_ReferenciaEntidad();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.uniandes.piladsl.pila.Variable#getExpresion <em>Expresion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expresion</em>'.
   * @see co.edu.uniandes.piladsl.pila.Variable#getExpresion()
   * @see #getVariable()
   * @generated
   */
  EReference getVariable_Expresion();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.piladsl.pila.Condicion <em>Condicion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condicion</em>'.
   * @see co.edu.uniandes.piladsl.pila.Condicion
   * @generated
   */
  EClass getCondicion();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.piladsl.pila.Condicion#getCondicionSi <em>Condicion Si</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condicion Si</em>'.
   * @see co.edu.uniandes.piladsl.pila.Condicion#getCondicionSi()
   * @see #getCondicion()
   * @generated
   */
  EAttribute getCondicion_CondicionSi();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.uniandes.piladsl.pila.Condicion#getExpresionCondicion <em>Expresion Condicion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expresion Condicion</em>'.
   * @see co.edu.uniandes.piladsl.pila.Condicion#getExpresionCondicion()
   * @see #getCondicion()
   * @generated
   */
  EReference getCondicion_ExpresionCondicion();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.piladsl.pila.Condicion#getCondicionSiNinguno <em>Condicion Si Ninguno</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condicion Si Ninguno</em>'.
   * @see co.edu.uniandes.piladsl.pila.Condicion#getCondicionSiNinguno()
   * @see #getCondicion()
   * @generated
   */
  EAttribute getCondicion_CondicionSiNinguno();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.uniandes.piladsl.pila.Condicion#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see co.edu.uniandes.piladsl.pila.Condicion#getVariables()
   * @see #getCondicion()
   * @generated
   */
  EReference getCondicion_Variables();

  /**
   * Returns the meta object for the reference '{@link co.edu.uniandes.piladsl.pila.Condicion#getAsignacionVariable <em>Asignacion Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Asignacion Variable</em>'.
   * @see co.edu.uniandes.piladsl.pila.Condicion#getAsignacionVariable()
   * @see #getCondicion()
   * @generated
   */
  EReference getCondicion_AsignacionVariable();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.uniandes.piladsl.pila.Condicion#getExpresion <em>Expresion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expresion</em>'.
   * @see co.edu.uniandes.piladsl.pila.Condicion#getExpresion()
   * @see #getCondicion()
   * @generated
   */
  EReference getCondicion_Expresion();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.uniandes.piladsl.pila.Condicion#getSubCondiciones <em>Sub Condiciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sub Condiciones</em>'.
   * @see co.edu.uniandes.piladsl.pila.Condicion#getSubCondiciones()
   * @see #getCondicion()
   * @generated
   */
  EReference getCondicion_SubCondiciones();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.uniandes.piladsl.pila.Condicion#getExpresionRetorno <em>Expresion Retorno</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expresion Retorno</em>'.
   * @see co.edu.uniandes.piladsl.pila.Condicion#getExpresionRetorno()
   * @see #getCondicion()
   * @generated
   */
  EReference getCondicion_ExpresionRetorno();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.piladsl.pila.Expresion <em>Expresion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expresion</em>'.
   * @see co.edu.uniandes.piladsl.pila.Expresion
   * @generated
   */
  EClass getExpresion();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.uniandes.piladsl.pila.Expresion#getIzquierda <em>Izquierda</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Izquierda</em>'.
   * @see co.edu.uniandes.piladsl.pila.Expresion#getIzquierda()
   * @see #getExpresion()
   * @generated
   */
  EReference getExpresion_Izquierda();

  /**
   * Returns the meta object for the attribute list '{@link co.edu.uniandes.piladsl.pila.Expresion#getOperador <em>Operador</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operador</em>'.
   * @see co.edu.uniandes.piladsl.pila.Expresion#getOperador()
   * @see #getExpresion()
   * @generated
   */
  EAttribute getExpresion_Operador();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.uniandes.piladsl.pila.Expresion#getDerechas <em>Derechas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Derechas</em>'.
   * @see co.edu.uniandes.piladsl.pila.Expresion#getDerechas()
   * @see #getExpresion()
   * @generated
   */
  EReference getExpresion_Derechas();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.piladsl.pila.Expresion#getEntero <em>Entero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Entero</em>'.
   * @see co.edu.uniandes.piladsl.pila.Expresion#getEntero()
   * @see #getExpresion()
   * @generated
   */
  EAttribute getExpresion_Entero();

  /**
   * Returns the meta object for the attribute '{@link co.edu.uniandes.piladsl.pila.Expresion#getReal <em>Real</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Real</em>'.
   * @see co.edu.uniandes.piladsl.pila.Expresion#getReal()
   * @see #getExpresion()
   * @generated
   */
  EAttribute getExpresion_Real();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.uniandes.piladsl.pila.Expresion#getNombreCalificado <em>Nombre Calificado</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nombre Calificado</em>'.
   * @see co.edu.uniandes.piladsl.pila.Expresion#getNombreCalificado()
   * @see #getExpresion()
   * @generated
   */
  EReference getExpresion_NombreCalificado();

  /**
   * Returns the meta object for class '{@link co.edu.uniandes.piladsl.pila.NombreCalificado <em>Nombre Calificado</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nombre Calificado</em>'.
   * @see co.edu.uniandes.piladsl.pila.NombreCalificado
   * @generated
   */
  EClass getNombreCalificado();

  /**
   * Returns the meta object for the attribute list '{@link co.edu.uniandes.piladsl.pila.NombreCalificado#getIdes <em>Ides</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Ides</em>'.
   * @see co.edu.uniandes.piladsl.pila.NombreCalificado#getIdes()
   * @see #getNombreCalificado()
   * @generated
   */
  EAttribute getNombreCalificado_Ides();

  /**
   * Returns the meta object for enum '{@link co.edu.uniandes.piladsl.pila.TipoDatoPrimitivo <em>Tipo Dato Primitivo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Tipo Dato Primitivo</em>'.
   * @see co.edu.uniandes.piladsl.pila.TipoDatoPrimitivo
   * @generated
   */
  EEnum getTipoDatoPrimitivo();

  /**
   * Returns the meta object for enum '{@link co.edu.uniandes.piladsl.pila.Operador <em>Operador</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Operador</em>'.
   * @see co.edu.uniandes.piladsl.pila.Operador
   * @generated
   */
  EEnum getOperador();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PilaFactory getPilaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link co.edu.uniandes.piladsl.pila.impl.PagoServicioImpl <em>Pago Servicio</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.piladsl.pila.impl.PagoServicioImpl
     * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getPagoServicio()
     * @generated
     */
    EClass PAGO_SERVICIO = eINSTANCE.getPagoServicio();

    /**
     * The meta object literal for the '<em><b>Entidades</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAGO_SERVICIO__ENTIDADES = eINSTANCE.getPagoServicio_Entidades();

    /**
     * The meta object literal for the '<em><b>Servicios Computo</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAGO_SERVICIO__SERVICIOS_COMPUTO = eINSTANCE.getPagoServicio_ServiciosComputo();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.piladsl.pila.impl.EntidadImpl <em>Entidad</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.piladsl.pila.impl.EntidadImpl
     * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getEntidad()
     * @generated
     */
    EClass ENTIDAD = eINSTANCE.getEntidad();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTIDAD__NAME = eINSTANCE.getEntidad_Name();

    /**
     * The meta object literal for the '<em><b>Atributos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTIDAD__ATRIBUTOS = eINSTANCE.getEntidad_Atributos();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.piladsl.pila.impl.AtributoImpl <em>Atributo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.piladsl.pila.impl.AtributoImpl
     * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getAtributo()
     * @generated
     */
    EClass ATRIBUTO = eINSTANCE.getAtributo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIBUTO__NAME = eINSTANCE.getAtributo_Name();

    /**
     * The meta object literal for the '<em><b>Tipo Primitivo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIBUTO__TIPO_PRIMITIVO = eINSTANCE.getAtributo_TipoPrimitivo();

    /**
     * The meta object literal for the '<em><b>Lista Llave Valor</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIBUTO__LISTA_LLAVE_VALOR = eINSTANCE.getAtributo_ListaLlaveValor();

    /**
     * The meta object literal for the '<em><b>Lista Entidad</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIBUTO__LISTA_ENTIDAD = eINSTANCE.getAtributo_ListaEntidad();

    /**
     * The meta object literal for the '<em><b>Referencia</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIBUTO__REFERENCIA = eINSTANCE.getAtributo_Referencia();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.piladsl.pila.impl.LlaveValorImpl <em>Llave Valor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.piladsl.pila.impl.LlaveValorImpl
     * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getLlaveValor()
     * @generated
     */
    EClass LLAVE_VALOR = eINSTANCE.getLlaveValor();

    /**
     * The meta object literal for the '<em><b>Llave</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LLAVE_VALOR__LLAVE = eINSTANCE.getLlaveValor_Llave();

    /**
     * The meta object literal for the '<em><b>Valor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LLAVE_VALOR__VALOR = eINSTANCE.getLlaveValor_Valor();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.piladsl.pila.impl.ServicioComputoImpl <em>Servicio Computo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.piladsl.pila.impl.ServicioComputoImpl
     * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getServicioComputo()
     * @generated
     */
    EClass SERVICIO_COMPUTO = eINSTANCE.getServicioComputo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVICIO_COMPUTO__NAME = eINSTANCE.getServicioComputo_Name();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVICIO_COMPUTO__VARIABLES = eINSTANCE.getServicioComputo_Variables();

    /**
     * The meta object literal for the '<em><b>Condiciones</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVICIO_COMPUTO__CONDICIONES = eINSTANCE.getServicioComputo_Condiciones();

    /**
     * The meta object literal for the '<em><b>Expresion Retorno</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVICIO_COMPUTO__EXPRESION_RETORNO = eINSTANCE.getServicioComputo_ExpresionRetorno();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.piladsl.pila.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.piladsl.pila.impl.VariableImpl
     * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '<em><b>Tipo Primitivo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__TIPO_PRIMITIVO = eINSTANCE.getVariable_TipoPrimitivo();

    /**
     * The meta object literal for the '<em><b>Referencia Entidad</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE__REFERENCIA_ENTIDAD = eINSTANCE.getVariable_ReferenciaEntidad();

    /**
     * The meta object literal for the '<em><b>Expresion</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE__EXPRESION = eINSTANCE.getVariable_Expresion();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.piladsl.pila.impl.CondicionImpl <em>Condicion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.piladsl.pila.impl.CondicionImpl
     * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getCondicion()
     * @generated
     */
    EClass CONDICION = eINSTANCE.getCondicion();

    /**
     * The meta object literal for the '<em><b>Condicion Si</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDICION__CONDICION_SI = eINSTANCE.getCondicion_CondicionSi();

    /**
     * The meta object literal for the '<em><b>Expresion Condicion</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDICION__EXPRESION_CONDICION = eINSTANCE.getCondicion_ExpresionCondicion();

    /**
     * The meta object literal for the '<em><b>Condicion Si Ninguno</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDICION__CONDICION_SI_NINGUNO = eINSTANCE.getCondicion_CondicionSiNinguno();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDICION__VARIABLES = eINSTANCE.getCondicion_Variables();

    /**
     * The meta object literal for the '<em><b>Asignacion Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDICION__ASIGNACION_VARIABLE = eINSTANCE.getCondicion_AsignacionVariable();

    /**
     * The meta object literal for the '<em><b>Expresion</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDICION__EXPRESION = eINSTANCE.getCondicion_Expresion();

    /**
     * The meta object literal for the '<em><b>Sub Condiciones</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDICION__SUB_CONDICIONES = eINSTANCE.getCondicion_SubCondiciones();

    /**
     * The meta object literal for the '<em><b>Expresion Retorno</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDICION__EXPRESION_RETORNO = eINSTANCE.getCondicion_ExpresionRetorno();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.piladsl.pila.impl.ExpresionImpl <em>Expresion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.piladsl.pila.impl.ExpresionImpl
     * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getExpresion()
     * @generated
     */
    EClass EXPRESION = eINSTANCE.getExpresion();

    /**
     * The meta object literal for the '<em><b>Izquierda</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESION__IZQUIERDA = eINSTANCE.getExpresion_Izquierda();

    /**
     * The meta object literal for the '<em><b>Operador</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESION__OPERADOR = eINSTANCE.getExpresion_Operador();

    /**
     * The meta object literal for the '<em><b>Derechas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESION__DERECHAS = eINSTANCE.getExpresion_Derechas();

    /**
     * The meta object literal for the '<em><b>Entero</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESION__ENTERO = eINSTANCE.getExpresion_Entero();

    /**
     * The meta object literal for the '<em><b>Real</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESION__REAL = eINSTANCE.getExpresion_Real();

    /**
     * The meta object literal for the '<em><b>Nombre Calificado</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESION__NOMBRE_CALIFICADO = eINSTANCE.getExpresion_NombreCalificado();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.piladsl.pila.impl.NombreCalificadoImpl <em>Nombre Calificado</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.piladsl.pila.impl.NombreCalificadoImpl
     * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getNombreCalificado()
     * @generated
     */
    EClass NOMBRE_CALIFICADO = eINSTANCE.getNombreCalificado();

    /**
     * The meta object literal for the '<em><b>Ides</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOMBRE_CALIFICADO__IDES = eINSTANCE.getNombreCalificado_Ides();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.piladsl.pila.TipoDatoPrimitivo <em>Tipo Dato Primitivo</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.piladsl.pila.TipoDatoPrimitivo
     * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getTipoDatoPrimitivo()
     * @generated
     */
    EEnum TIPO_DATO_PRIMITIVO = eINSTANCE.getTipoDatoPrimitivo();

    /**
     * The meta object literal for the '{@link co.edu.uniandes.piladsl.pila.Operador <em>Operador</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.uniandes.piladsl.pila.Operador
     * @see co.edu.uniandes.piladsl.pila.impl.PilaPackageImpl#getOperador()
     * @generated
     */
    EEnum OPERADOR = eINSTANCE.getOperador();

  }

} //PilaPackage
