/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.ui;

import co.edu.uniandes.piladsl.ui.AbstractPilaUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PilaUiModule extends AbstractPilaUiModule {
  public PilaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
