/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.validation;

import co.edu.uniandes.piladsl.validation.AbstractPilaValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PilaValidator extends AbstractPilaValidator {
}
