/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.pila;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expresion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link co.edu.uniandes.piladsl.pila.Expresion#getExpresionTerminal <em>Expresion Terminal</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.Expresion#getOperacion <em>Operacion</em>}</li>
 * </ul>
 * </p>
 *
 * @see co.edu.uniandes.piladsl.pila.PilaPackage#getExpresion()
 * @model
 * @generated
 */
public interface Expresion extends EObject
{
  /**
   * Returns the value of the '<em><b>Expresion Terminal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expresion Terminal</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expresion Terminal</em>' containment reference.
   * @see #setExpresionTerminal(ExpresionTerminal)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getExpresion_ExpresionTerminal()
   * @model containment="true"
   * @generated
   */
  ExpresionTerminal getExpresionTerminal();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.Expresion#getExpresionTerminal <em>Expresion Terminal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expresion Terminal</em>' containment reference.
   * @see #getExpresionTerminal()
   * @generated
   */
  void setExpresionTerminal(ExpresionTerminal value);

  /**
   * Returns the value of the '<em><b>Operacion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operacion</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operacion</em>' containment reference.
   * @see #setOperacion(Operacion)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getExpresion_Operacion()
   * @model containment="true"
   * @generated
   */
  Operacion getOperacion();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.Expresion#getOperacion <em>Operacion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operacion</em>' containment reference.
   * @see #getOperacion()
   * @generated
   */
  void setOperacion(Operacion value);

} // Expresion
