/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.pila;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expresion Terminal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link co.edu.uniandes.piladsl.pila.ExpresionTerminal#getEntero <em>Entero</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.ExpresionTerminal#getReal <em>Real</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.ExpresionTerminal#getNombreCalificado <em>Nombre Calificado</em>}</li>
 * </ul>
 * </p>
 *
 * @see co.edu.uniandes.piladsl.pila.PilaPackage#getExpresionTerminal()
 * @model
 * @generated
 */
public interface ExpresionTerminal extends EObject
{
  /**
   * Returns the value of the '<em><b>Entero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entero</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entero</em>' attribute.
   * @see #setEntero(int)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getExpresionTerminal_Entero()
   * @model
   * @generated
   */
  int getEntero();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.ExpresionTerminal#getEntero <em>Entero</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entero</em>' attribute.
   * @see #getEntero()
   * @generated
   */
  void setEntero(int value);

  /**
   * Returns the value of the '<em><b>Real</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Real</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Real</em>' attribute.
   * @see #setReal(String)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getExpresionTerminal_Real()
   * @model
   * @generated
   */
  String getReal();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.ExpresionTerminal#getReal <em>Real</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Real</em>' attribute.
   * @see #getReal()
   * @generated
   */
  void setReal(String value);

  /**
   * Returns the value of the '<em><b>Nombre Calificado</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nombre Calificado</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre Calificado</em>' containment reference.
   * @see #setNombreCalificado(NombreCalificado)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getExpresionTerminal_NombreCalificado()
   * @model containment="true"
   * @generated
   */
  NombreCalificado getNombreCalificado();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.ExpresionTerminal#getNombreCalificado <em>Nombre Calificado</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre Calificado</em>' containment reference.
   * @see #getNombreCalificado()
   * @generated
   */
  void setNombreCalificado(NombreCalificado value);

} // ExpresionTerminal
