/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.pila;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operacion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link co.edu.uniandes.piladsl.pila.Operacion#getIzquierda <em>Izquierda</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.Operacion#getOperador <em>Operador</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.Operacion#getDerecha <em>Derecha</em>}</li>
 * </ul>
 * </p>
 *
 * @see co.edu.uniandes.piladsl.pila.PilaPackage#getOperacion()
 * @model
 * @generated
 */
public interface Operacion extends EObject
{
  /**
   * Returns the value of the '<em><b>Izquierda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Izquierda</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Izquierda</em>' containment reference.
   * @see #setIzquierda(ExpresionTerminal)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getOperacion_Izquierda()
   * @model containment="true"
   * @generated
   */
  ExpresionTerminal getIzquierda();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.Operacion#getIzquierda <em>Izquierda</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Izquierda</em>' containment reference.
   * @see #getIzquierda()
   * @generated
   */
  void setIzquierda(ExpresionTerminal value);

  /**
   * Returns the value of the '<em><b>Operador</b></em>' attribute.
   * The literals are from the enumeration {@link co.edu.uniandes.piladsl.pila.Operador}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operador</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operador</em>' attribute.
   * @see co.edu.uniandes.piladsl.pila.Operador
   * @see #setOperador(Operador)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getOperacion_Operador()
   * @model
   * @generated
   */
  Operador getOperador();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.Operacion#getOperador <em>Operador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operador</em>' attribute.
   * @see co.edu.uniandes.piladsl.pila.Operador
   * @see #getOperador()
   * @generated
   */
  void setOperador(Operador value);

  /**
   * Returns the value of the '<em><b>Derecha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Derecha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Derecha</em>' containment reference.
   * @see #setDerecha(ExpresionTerminal)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getOperacion_Derecha()
   * @model containment="true"
   * @generated
   */
  ExpresionTerminal getDerecha();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.Operacion#getDerecha <em>Derecha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Derecha</em>' containment reference.
   * @see #getDerecha()
   * @generated
   */
  void setDerecha(ExpresionTerminal value);

} // Operacion
