/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.pila;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Servicio Computo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link co.edu.uniandes.piladsl.pila.ServicioComputo#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.ServicioComputo#getVariables <em>Variables</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.ServicioComputo#getCondiciones <em>Condiciones</em>}</li>
 *   <li>{@link co.edu.uniandes.piladsl.pila.ServicioComputo#getExpresionRetorno <em>Expresion Retorno</em>}</li>
 * </ul>
 * </p>
 *
 * @see co.edu.uniandes.piladsl.pila.PilaPackage#getServicioComputo()
 * @model
 * @generated
 */
public interface ServicioComputo extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getServicioComputo_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.ServicioComputo#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference list.
   * The list contents are of type {@link co.edu.uniandes.piladsl.pila.Variable}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variables</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference list.
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getServicioComputo_Variables()
   * @model containment="true"
   * @generated
   */
  EList<Variable> getVariables();

  /**
   * Returns the value of the '<em><b>Condiciones</b></em>' containment reference list.
   * The list contents are of type {@link co.edu.uniandes.piladsl.pila.Condicion}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condiciones</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condiciones</em>' containment reference list.
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getServicioComputo_Condiciones()
   * @model containment="true"
   * @generated
   */
  EList<Condicion> getCondiciones();

  /**
   * Returns the value of the '<em><b>Expresion Retorno</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expresion Retorno</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expresion Retorno</em>' containment reference.
   * @see #setExpresionRetorno(Expresion)
   * @see co.edu.uniandes.piladsl.pila.PilaPackage#getServicioComputo_ExpresionRetorno()
   * @model containment="true"
   * @generated
   */
  Expresion getExpresionRetorno();

  /**
   * Sets the value of the '{@link co.edu.uniandes.piladsl.pila.ServicioComputo#getExpresionRetorno <em>Expresion Retorno</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expresion Retorno</em>' containment reference.
   * @see #getExpresionRetorno()
   * @generated
   */
  void setExpresionRetorno(Expresion value);

} // ServicioComputo
