/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.piladsl.pila;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Tipo Dato Primitivo</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see co.edu.uniandes.piladsl.pila.PilaPackage#getTipoDatoPrimitivo()
 * @model
 * @generated
 */
public enum TipoDatoPrimitivo implements Enumerator
{
  /**
   * The '<em><b>NO ASIGNADO</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NO_ASIGNADO_VALUE
   * @generated
   * @ordered
   */
  NO_ASIGNADO(0, "NO_ASIGNADO", "NoAsignado"),

  /**
   * The '<em><b>CADENA CARACTERES</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CADENA_CARACTERES_VALUE
   * @generated
   * @ordered
   */
  CADENA_CARACTERES(1, "CADENA_CARACTERES", "CadenaCaracteres"),

  /**
   * The '<em><b>ENTERO</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ENTERO_VALUE
   * @generated
   * @ordered
   */
  ENTERO(2, "ENTERO", "Entero"),

  /**
   * The '<em><b>FLOTANTE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FLOTANTE_VALUE
   * @generated
   * @ordered
   */
  FLOTANTE(3, "FLOTANTE", "Flotante"),

  /**
   * The '<em><b>FECHA</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FECHA_VALUE
   * @generated
   * @ordered
   */
  FECHA(4, "FECHA", "Fecha"),

  /**
   * The '<em><b>BOOLEANO</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BOOLEANO_VALUE
   * @generated
   * @ordered
   */
  BOOLEANO(5, "BOOLEANO", "Booleano");

  /**
   * The '<em><b>NO ASIGNADO</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>NO ASIGNADO</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #NO_ASIGNADO
   * @model literal="NoAsignado"
   * @generated
   * @ordered
   */
  public static final int NO_ASIGNADO_VALUE = 0;

  /**
   * The '<em><b>CADENA CARACTERES</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>CADENA CARACTERES</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CADENA_CARACTERES
   * @model literal="CadenaCaracteres"
   * @generated
   * @ordered
   */
  public static final int CADENA_CARACTERES_VALUE = 1;

  /**
   * The '<em><b>ENTERO</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ENTERO</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ENTERO
   * @model literal="Entero"
   * @generated
   * @ordered
   */
  public static final int ENTERO_VALUE = 2;

  /**
   * The '<em><b>FLOTANTE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FLOTANTE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FLOTANTE
   * @model literal="Flotante"
   * @generated
   * @ordered
   */
  public static final int FLOTANTE_VALUE = 3;

  /**
   * The '<em><b>FECHA</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FECHA</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FECHA
   * @model literal="Fecha"
   * @generated
   * @ordered
   */
  public static final int FECHA_VALUE = 4;

  /**
   * The '<em><b>BOOLEANO</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>BOOLEANO</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #BOOLEANO
   * @model literal="Booleano"
   * @generated
   * @ordered
   */
  public static final int BOOLEANO_VALUE = 5;

  /**
   * An array of all the '<em><b>Tipo Dato Primitivo</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final TipoDatoPrimitivo[] VALUES_ARRAY =
    new TipoDatoPrimitivo[]
    {
      NO_ASIGNADO,
      CADENA_CARACTERES,
      ENTERO,
      FLOTANTE,
      FECHA,
      BOOLEANO,
    };

  /**
   * A public read-only list of all the '<em><b>Tipo Dato Primitivo</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<TipoDatoPrimitivo> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Tipo Dato Primitivo</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static TipoDatoPrimitivo get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TipoDatoPrimitivo result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Tipo Dato Primitivo</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static TipoDatoPrimitivo getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TipoDatoPrimitivo result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Tipo Dato Primitivo</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static TipoDatoPrimitivo get(int value)
  {
    switch (value)
    {
      case NO_ASIGNADO_VALUE: return NO_ASIGNADO;
      case CADENA_CARACTERES_VALUE: return CADENA_CARACTERES;
      case ENTERO_VALUE: return ENTERO;
      case FLOTANTE_VALUE: return FLOTANTE;
      case FECHA_VALUE: return FECHA;
      case BOOLEANO_VALUE: return BOOLEANO;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private TipoDatoPrimitivo(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //TipoDatoPrimitivo
